stages:
  data_ingestion:
    cmd: .\dvc_pipeline\Scripts\python src\data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion
    outs:
      - data/raw

  data_pre-processing:
    cmd: .\dvc_pipeline\Scripts\python src\data_pre-processing.py
    deps:
      - data/raw
      - src/data_pre-processing.py
    outs:
      - data/interim

  feature_engineering:
    cmd: .\dvc_pipeline\Scripts\python src\feature_engineering.py
    deps:
      - data/raw
      - src/feature_engineering.py
    params:
      - feature_engineering
    outs:
      - data/processed

  model_building:
    cmd: .\dvc_pipeline\Scripts\python src\model_building.py
    deps:
      - data/processed
      - src/model_building.py
    params:
      - model_building
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: .\dvc_pipeline\Scripts\python src\model_evaluation.py
    deps:
      - models/model.pkl
      - src/model_evaluation.py
    metrics:
      - dvclive/metrics.json